### ISSUE TITLE
Make symlinks of the QC'ed short read at the start to simplify logging

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#158]

**Comment by LeeBergstrand** [comment]
@jmtsuji What did you mean by this?

**Comment by jmtsuji** [comment]
@LeeBergstrand Thanks for flagging this old issue. This is no longer relevant, because we added a short read QC module. An early version of rotary directly used the user-supplied short reads for all polishing steps in the pipeline (no QC). This was not good for reproducibility, because a symlink or copy of the short read files were never saved in the actual run folder. Closing as completed.
