### ISSUE TITLE
Add option for nano-corr in flye / repair script

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#159]

**Comment by LeeBergstrand** [comment]
@jmtsuji What was this about? Allowing pre-corrected reads as input? or using the repaired reads during the end repair? Has this been addressed?

**Comment by jmtsuji** [comment]
@LeeBergstrand This must have been about using pre-corrected reads as input. I might have added this to-do item because `circlator` had a pre-corrected read input option. However, I no longer think this feature relevant, given accuracy gains in Nanopore sequencing. I think we could easily add this option in the future if a user needs it for an edge case, but I don't foresee this being a common way to use rotary. Closing as completed.
