### ISSUE TITLE
Make eggnog mapper use mmseqs2?

### ISSUE THREAD

**Issue by LeeBergstrand** [jmtsuji/rotary#74]
### Problem Description

Eggnog mapper takes a long time to run.

### Problem Solution

I was going through eggnog mapper's command line options. You have the option of running it with diamond, mmseqs2, or hammer. My understanding is that mmseqs2 is faster than diamond. I was wondering why the diamond option was chosen as the eggnog search tool? Was there sensitivity issues?

**Comment by jmtsuji** [comment]
@LeeBergstrand Just checked the [eggnog-mapper article](https://doi.org/10.1093/molbev/msab293), and it appears that mmseqs2 is faster than DIAMOND with non-huge datasets and has comparable sensitivity to DIAMOND, based on their testing. Because we are using a genome annotation pipeline, let's use mmseqs!

**Comment by LeeBergstrand** [comment]
@jmtsuji Okay, I will address this.

**Comment by LeeBergstrand** [comment]
@jmtsuji Addressed in https://github.com/jmtsuji/rotary/pull/73/commits/dd96bbc1516b0c95d40068091c9173b702419e5b
